// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetDexQL.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace netdexQL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NetDexQL.Data.Models.MonType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_types");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_types_name");

                    b.ToTable("types", (string)null);
                });

            modelBuilder.Entity("NetDexQL.Data.Models.Pokemon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("BaseExperience")
                        .HasColumnType("integer")
                        .HasColumnName("base_experience");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_pokemon");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_pokemon_name");

                    b.ToTable("pokemon", (string)null);
                });

            modelBuilder.Entity("NetDexQL.Data.Models.PokemonOnType", b =>
                {
                    b.Property<Guid>("MonTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("mon_type_id");

                    b.Property<Guid>("PokemonId")
                        .HasColumnType("uuid")
                        .HasColumnName("pokemon_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.HasKey("MonTypeId", "PokemonId")
                        .HasName("pk_pokemon_on_types");

                    b.HasIndex("PokemonId")
                        .HasDatabaseName("ix_pokemon_on_types_pokemon_id");

                    b.ToTable("pokemon_on_types", (string)null);
                });

            modelBuilder.Entity("NetDexQL.Data.Models.PokemonOnType", b =>
                {
                    b.HasOne("NetDexQL.Data.Models.MonType", null)
                        .WithMany("PokemonTypes")
                        .HasForeignKey("MonTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pokemon_on_types_types_mon_type_id");

                    b.HasOne("NetDexQL.Data.Models.Pokemon", null)
                        .WithMany("PokemonTypes")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pokemon_on_types_pokemon_pokemon_id");
                });

            modelBuilder.Entity("NetDexQL.Data.Models.MonType", b =>
                {
                    b.Navigation("PokemonTypes");
                });

            modelBuilder.Entity("NetDexQL.Data.Models.Pokemon", b =>
                {
                    b.Navigation("PokemonTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
